/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'unplugin-vue-router/types'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    'root': RouteRecordInfo<'root', '/', Record<never, never>, Record<never, never>>,
    '$error': RouteRecordInfo<'$error', '/:error(.*)', { error: ParamValue<true> }, { error: ParamValue<false> }>,
    'home-all-product-ratio': RouteRecordInfo<'home-all-product-ratio', '/home/AllProductRatio', Record<never, never>, Record<never, never>>,
    'home-haz-product-category-ratio': RouteRecordInfo<'home-haz-product-category-ratio', '/home/HazProductCategoryRatio', Record<never, never>, Record<never, never>>,
    'home-monthly-migration-stats': RouteRecordInfo<'home-monthly-migration-stats', '/home/MonthlyMigrationStats', Record<never, never>, Record<never, never>>,
    'home-transfer-dashboard': RouteRecordInfo<'home-transfer-dashboard', '/home/TransferDashboard', Record<never, never>, Record<never, never>>,
    'login': RouteRecordInfo<'login', '/login', Record<never, never>, Record<never, never>>,
    'migration-data-migration': RouteRecordInfo<'migration-data-migration', '/migration/data-migration', Record<never, never>, Record<never, never>>,
    'migration-results': RouteRecordInfo<'migration-results', '/migration/results', Record<never, never>, Record<never, never>>,
    'not-authorized': RouteRecordInfo<'not-authorized', '/not-authorized', Record<never, never>, Record<never, never>>,
    'product-all-product': RouteRecordInfo<'product-all-product', '/product/all-product', Record<never, never>, Record<never, never>>,
  }
}
