/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'unplugin-vue-router/types'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    'root': RouteRecordInfo<'root', '/', Record<never, never>, Record<never, never>>,
    '$error': RouteRecordInfo<'$error', '/:error(.*)', { error: ParamValue<true> }, { error: ParamValue<false> }>,
    'ds-base-dialog': RouteRecordInfo<'ds-base-dialog', '/ds/BaseDialog', Record<never, never>, Record<never, never>>,
    'ds-company-dialog': RouteRecordInfo<'ds-company-dialog', '/ds/CompanyDialog', Record<never, never>, Record<never, never>>,
    'ds-home-home-overview': RouteRecordInfo<'ds-home-home-overview', '/ds/home/HomeOverview', Record<never, never>, Record<never, never>>,
    'ds-home-transfer-dashboard': RouteRecordInfo<'ds-home-transfer-dashboard', '/ds/home/TransferDashboard', Record<never, never>, Record<never, never>>,
    'ds-inspection-dialog': RouteRecordInfo<'ds-inspection-dialog', '/ds/InspectionDialog', Record<never, never>, Record<never, never>>,
    'ds-migration-migrate': RouteRecordInfo<'ds-migration-migrate', '/ds/migration/migrate', Record<never, never>, Record<never, never>>,
    'ds-migration-results': RouteRecordInfo<'ds-migration-results', '/ds/migration/results', Record<never, never>, Record<never, never>>,
    'ds-product': RouteRecordInfo<'ds-product', '/ds/product', Record<never, never>, Record<never, never>>,
    'ds-product-all-prd': RouteRecordInfo<'ds-product-all-prd', '/ds/product/all-prd', Record<never, never>, Record<never, never>>,
    'ds-product-haz-prd': RouteRecordInfo<'ds-product-haz-prd', '/ds/product/haz-prd', Record<never, never>, Record<never, never>>,
    'ds-product-nonhaz-prd': RouteRecordInfo<'ds-product-nonhaz-prd', '/ds/product/nonhaz-prd', Record<never, never>, Record<never, never>>,
    'ds-result-dialog': RouteRecordInfo<'ds-result-dialog', '/ds/ResultDialog', Record<never, never>, Record<never, never>>,
    'login': RouteRecordInfo<'login', '/login', Record<never, never>, Record<never, never>>,
    'not-authorized': RouteRecordInfo<'not-authorized', '/not-authorized', Record<never, never>, Record<never, never>>,
  }
}
